/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.records;


import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnOrder;

import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdnOrderRecord extends UpdatableRecordImpl<OdnOrderRecord> implements Record7<UInteger, UInteger, UInteger, String, LocalDate, String, UInteger> {

    private static final long serialVersionUID = 1744535370;

    /**
     * Setter for <code>ordernow.odn_order.id_order</code>.
     */
    public void setIdOrder(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>ordernow.odn_order.id_order</code>.
     */
    public UInteger getIdOrder() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>ordernow.odn_order.id_user</code>.
     */
    public void setIdUser(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>ordernow.odn_order.id_user</code>.
     */
    public UInteger getIdUser() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>ordernow.odn_order.id_restaurant</code>.
     */
    public void setIdRestaurant(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>ordernow.odn_order.id_restaurant</code>.
     */
    public UInteger getIdRestaurant() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>ordernow.odn_order.in_status_order</code>.
     */
    public void setInStatusOrder(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ordernow.odn_order.in_status_order</code>.
     */
    public String getInStatusOrder() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ordernow.odn_order.dt_order</code>.
     */
    public void setDtOrder(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>ordernow.odn_order.dt_order</code>.
     */
    public LocalDate getDtOrder() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>ordernow.odn_order.fl_aval</code>.
     */
    public void setFlAval(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ordernow.odn_order.fl_aval</code>.
     */
    public String getFlAval() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ordernow.odn_order.rating</code>.
     */
    public void setRating(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>ordernow.odn_order.rating</code>.
     */
    public UInteger getRating() {
        return (UInteger) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, UInteger, String, LocalDate, String, UInteger> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, UInteger, String, LocalDate, String, UInteger> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return OdnOrder.ODN_ORDER.ID_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return OdnOrder.ODN_ORDER.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return OdnOrder.ODN_ORDER.ID_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OdnOrder.ODN_ORDER.IN_STATUS_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field5() {
        return OdnOrder.ODN_ORDER.DT_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OdnOrder.ODN_ORDER.FL_AVAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return OdnOrder.ODN_ORDER.RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getInStatusOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component5() {
        return getDtOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFlAval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component7() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInStatusOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value5() {
        return getDtOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFlAval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderRecord value1(UInteger value) {
        setIdOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderRecord value2(UInteger value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderRecord value3(UInteger value) {
        setIdRestaurant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderRecord value4(String value) {
        setInStatusOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderRecord value5(LocalDate value) {
        setDtOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderRecord value6(String value) {
        setFlAval(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderRecord value7(UInteger value) {
        setRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderRecord values(UInteger value1, UInteger value2, UInteger value3, String value4, LocalDate value5, String value6, UInteger value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OdnOrderRecord
     */
    public OdnOrderRecord() {
        super(OdnOrder.ODN_ORDER);
    }

    /**
     * Create a detached, initialised OdnOrderRecord
     */
    public OdnOrderRecord(UInteger idOrder, UInteger idUser, UInteger idRestaurant, String inStatusOrder, LocalDate dtOrder, String flAval, UInteger rating) {
        super(OdnOrder.ODN_ORDER);

        set(0, idOrder);
        set(1, idUser);
        set(2, idRestaurant);
        set(3, inStatusOrder);
        set(4, dtOrder);
        set(5, flAval);
        set(6, rating);
    }
}
