/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.records;


import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnProduct;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdnProductRecord extends UpdatableRecordImpl<OdnProductRecord> implements Record4<UInteger, String, UInteger, BigDecimal> {

    private static final long serialVersionUID = -1176971677;

    /**
     * Setter for <code>ordernow.odn_product.id_product</code>.
     */
    public void setIdProduct(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>ordernow.odn_product.id_product</code>.
     */
    public UInteger getIdProduct() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>ordernow.odn_product.nm_product</code>.
     */
    public void setNmProduct(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ordernow.odn_product.nm_product</code>.
     */
    public String getNmProduct() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ordernow.odn_product.id_restaurant</code>.
     */
    public void setIdRestaurant(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>ordernow.odn_product.id_restaurant</code>.
     */
    public UInteger getIdRestaurant() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>ordernow.odn_product.price_product</code>.
     */
    public void setPriceProduct(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>ordernow.odn_product.price_product</code>.
     */
    public BigDecimal getPriceProduct() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, UInteger, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, UInteger, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return OdnProduct.ODN_PRODUCT.ID_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OdnProduct.ODN_PRODUCT.NM_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return OdnProduct.ODN_PRODUCT.ID_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return OdnProduct.ODN_PRODUCT.PRICE_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNmProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getPriceProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNmProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPriceProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnProductRecord value1(UInteger value) {
        setIdProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnProductRecord value2(String value) {
        setNmProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnProductRecord value3(UInteger value) {
        setIdRestaurant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnProductRecord value4(BigDecimal value) {
        setPriceProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnProductRecord values(UInteger value1, String value2, UInteger value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OdnProductRecord
     */
    public OdnProductRecord() {
        super(OdnProduct.ODN_PRODUCT);
    }

    /**
     * Create a detached, initialised OdnProductRecord
     */
    public OdnProductRecord(UInteger idProduct, String nmProduct, UInteger idRestaurant, BigDecimal priceProduct) {
        super(OdnProduct.ODN_PRODUCT);

        set(0, idProduct);
        set(1, nmProduct);
        set(2, idRestaurant);
        set(3, priceProduct);
    }
}
