/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.records;


import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnRestaurant;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdnRestaurantRecord extends UpdatableRecordImpl<OdnRestaurantRecord> implements Record3<UInteger, String, UInteger> {

    private static final long serialVersionUID = 410283131;

    /**
     * Setter for <code>ordernow.odn_restaurant.id_restaurant</code>.
     */
    public void setIdRestaurant(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>ordernow.odn_restaurant.id_restaurant</code>.
     */
    public UInteger getIdRestaurant() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>ordernow.odn_restaurant.nm_restaurant</code>.
     */
    public void setNmRestaurant(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ordernow.odn_restaurant.nm_restaurant</code>.
     */
    public String getNmRestaurant() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ordernow.odn_restaurant.id_dishe</code>.
     */
    public void setIdDishe(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>ordernow.odn_restaurant.id_dishe</code>.
     */
    public UInteger getIdDishe() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, String, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, String, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return OdnRestaurant.ODN_RESTAURANT.ID_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OdnRestaurant.ODN_RESTAURANT.NM_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return OdnRestaurant.ODN_RESTAURANT.ID_DISHE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNmRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getIdDishe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNmRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getIdDishe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnRestaurantRecord value1(UInteger value) {
        setIdRestaurant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnRestaurantRecord value2(String value) {
        setNmRestaurant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnRestaurantRecord value3(UInteger value) {
        setIdDishe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnRestaurantRecord values(UInteger value1, String value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OdnRestaurantRecord
     */
    public OdnRestaurantRecord() {
        super(OdnRestaurant.ODN_RESTAURANT);
    }

    /**
     * Create a detached, initialised OdnRestaurantRecord
     */
    public OdnRestaurantRecord(UInteger idRestaurant, String nmRestaurant, UInteger idDishe) {
        super(OdnRestaurant.ODN_RESTAURANT);

        set(0, idRestaurant);
        set(1, nmRestaurant);
        set(2, idDishe);
    }
}
