/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.mysql.model.jooq;


import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnDishe;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnOrder;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnOrderProduct;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnProduct;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnRestaurant;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnUser;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>ordernow</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ODN_DISHE_PRIMARY = Indexes0.ODN_DISHE_PRIMARY;
    public static final Index ODN_ORDER_ID_RESTAURANT = Indexes0.ODN_ORDER_ID_RESTAURANT;
    public static final Index ODN_ORDER_ID_USER = Indexes0.ODN_ORDER_ID_USER;
    public static final Index ODN_ORDER_PRIMARY = Indexes0.ODN_ORDER_PRIMARY;
    public static final Index ODN_ORDER_PRODUCT_ID_ORDER = Indexes0.ODN_ORDER_PRODUCT_ID_ORDER;
    public static final Index ODN_ORDER_PRODUCT_ID_PRODUCT = Indexes0.ODN_ORDER_PRODUCT_ID_PRODUCT;
    public static final Index ODN_ORDER_PRODUCT_PRIMARY = Indexes0.ODN_ORDER_PRODUCT_PRIMARY;
    public static final Index ODN_PRODUCT_ID_RESTAURANT = Indexes0.ODN_PRODUCT_ID_RESTAURANT;
    public static final Index ODN_PRODUCT_PRIMARY = Indexes0.ODN_PRODUCT_PRIMARY;
    public static final Index ODN_RESTAURANT_ID_DISHE = Indexes0.ODN_RESTAURANT_ID_DISHE;
    public static final Index ODN_RESTAURANT_PRIMARY = Indexes0.ODN_RESTAURANT_PRIMARY;
    public static final Index ODN_USER_PRIMARY = Indexes0.ODN_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ODN_DISHE_PRIMARY = Internal.createIndex("PRIMARY", OdnDishe.ODN_DISHE, new OrderField[] { OdnDishe.ODN_DISHE.ID_DISHE }, true);
        public static Index ODN_ORDER_ID_RESTAURANT = Internal.createIndex("id_restaurant", OdnOrder.ODN_ORDER, new OrderField[] { OdnOrder.ODN_ORDER.ID_RESTAURANT }, false);
        public static Index ODN_ORDER_ID_USER = Internal.createIndex("id_user", OdnOrder.ODN_ORDER, new OrderField[] { OdnOrder.ODN_ORDER.ID_USER }, false);
        public static Index ODN_ORDER_PRIMARY = Internal.createIndex("PRIMARY", OdnOrder.ODN_ORDER, new OrderField[] { OdnOrder.ODN_ORDER.ID_ORDER }, true);
        public static Index ODN_ORDER_PRODUCT_ID_ORDER = Internal.createIndex("id_order", OdnOrderProduct.ODN_ORDER_PRODUCT, new OrderField[] { OdnOrderProduct.ODN_ORDER_PRODUCT.ID_ORDER }, false);
        public static Index ODN_ORDER_PRODUCT_ID_PRODUCT = Internal.createIndex("id_product", OdnOrderProduct.ODN_ORDER_PRODUCT, new OrderField[] { OdnOrderProduct.ODN_ORDER_PRODUCT.ID_PRODUCT }, false);
        public static Index ODN_ORDER_PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", OdnOrderProduct.ODN_ORDER_PRODUCT, new OrderField[] { OdnOrderProduct.ODN_ORDER_PRODUCT.ID_ORDER_PRODUCT }, true);
        public static Index ODN_PRODUCT_ID_RESTAURANT = Internal.createIndex("id_restaurant", OdnProduct.ODN_PRODUCT, new OrderField[] { OdnProduct.ODN_PRODUCT.ID_RESTAURANT }, false);
        public static Index ODN_PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", OdnProduct.ODN_PRODUCT, new OrderField[] { OdnProduct.ODN_PRODUCT.ID_PRODUCT }, true);
        public static Index ODN_RESTAURANT_ID_DISHE = Internal.createIndex("id_dishe", OdnRestaurant.ODN_RESTAURANT, new OrderField[] { OdnRestaurant.ODN_RESTAURANT.ID_DISHE }, false);
        public static Index ODN_RESTAURANT_PRIMARY = Internal.createIndex("PRIMARY", OdnRestaurant.ODN_RESTAURANT, new OrderField[] { OdnRestaurant.ODN_RESTAURANT.ID_RESTAURANT }, true);
        public static Index ODN_USER_PRIMARY = Internal.createIndex("PRIMARY", OdnUser.ODN_USER, new OrderField[] { OdnUser.ODN_USER.ID_USER }, true);
    }
}
