/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.mysql.model.jooq;


import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnDishe;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnOrder;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnOrderProduct;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnProduct;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnRestaurant;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ordernow
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ordernow.odn_dishe</code>.
     */
    public static final OdnDishe ODN_DISHE = br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnDishe.ODN_DISHE;

    /**
     * The table <code>ordernow.odn_order</code>.
     */
    public static final OdnOrder ODN_ORDER = br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnOrder.ODN_ORDER;

    /**
     * The table <code>ordernow.odn_order_product</code>.
     */
    public static final OdnOrderProduct ODN_ORDER_PRODUCT = br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnOrderProduct.ODN_ORDER_PRODUCT;

    /**
     * The table <code>ordernow.odn_product</code>.
     */
    public static final OdnProduct ODN_PRODUCT = br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnProduct.ODN_PRODUCT;

    /**
     * The table <code>ordernow.odn_restaurant</code>.
     */
    public static final OdnRestaurant ODN_RESTAURANT = br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnRestaurant.ODN_RESTAURANT;

    /**
     * The table <code>ordernow.odn_user</code>.
     */
    public static final OdnUser ODN_USER = br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.OdnUser.ODN_USER;
}
