/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables;


import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.Indexes;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.Keys;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.Ordernow;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.records.OdnDisheRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdnDishe extends TableImpl<OdnDisheRecord> {

    private static final long serialVersionUID = -315180051;

    /**
     * The reference instance of <code>ordernow.odn_dishe</code>
     */
    public static final OdnDishe ODN_DISHE = new OdnDishe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OdnDisheRecord> getRecordType() {
        return OdnDisheRecord.class;
    }

    /**
     * The column <code>ordernow.odn_dishe.id_dishe</code>.
     */
    public final TableField<OdnDisheRecord, UInteger> ID_DISHE = createField("id_dishe", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>ordernow.odn_dishe.nm_dishe</code>.
     */
    public final TableField<OdnDisheRecord, String> NM_DISHE = createField("nm_dishe", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>ordernow.odn_dishe</code> table reference
     */
    public OdnDishe() {
        this(DSL.name("odn_dishe"), null);
    }

    /**
     * Create an aliased <code>ordernow.odn_dishe</code> table reference
     */
    public OdnDishe(String alias) {
        this(DSL.name(alias), ODN_DISHE);
    }

    /**
     * Create an aliased <code>ordernow.odn_dishe</code> table reference
     */
    public OdnDishe(Name alias) {
        this(alias, ODN_DISHE);
    }

    private OdnDishe(Name alias, Table<OdnDisheRecord> aliased) {
        this(alias, aliased, null);
    }

    private OdnDishe(Name alias, Table<OdnDisheRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OdnDishe(Table<O> child, ForeignKey<O, OdnDisheRecord> key) {
        super(child, key, ODN_DISHE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ordernow.ORDERNOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ODN_DISHE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OdnDisheRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_ODN_DISHE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OdnDisheRecord> getPrimaryKey() {
        return Keys.KEY_ODN_DISHE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OdnDisheRecord>> getKeys() {
        return Arrays.<UniqueKey<OdnDisheRecord>>asList(Keys.KEY_ODN_DISHE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnDishe as(String alias) {
        return new OdnDishe(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnDishe as(Name alias) {
        return new OdnDishe(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OdnDishe rename(String name) {
        return new OdnDishe(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdnDishe rename(Name name) {
        return new OdnDishe(name, null);
    }
}
