/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables;


import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.Indexes;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.Keys;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.Ordernow;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.records.OdnOrderProductRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdnOrderProduct extends TableImpl<OdnOrderProductRecord> {

    private static final long serialVersionUID = -1941945493;

    /**
     * The reference instance of <code>ordernow.odn_order_product</code>
     */
    public static final OdnOrderProduct ODN_ORDER_PRODUCT = new OdnOrderProduct();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OdnOrderProductRecord> getRecordType() {
        return OdnOrderProductRecord.class;
    }

    /**
     * The column <code>ordernow.odn_order_product.id_order_product</code>.
     */
    public final TableField<OdnOrderProductRecord, UInteger> ID_ORDER_PRODUCT = createField("id_order_product", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>ordernow.odn_order_product.id_order</code>.
     */
    public final TableField<OdnOrderProductRecord, UInteger> ID_ORDER = createField("id_order", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ordernow.odn_order_product.id_product</code>.
     */
    public final TableField<OdnOrderProductRecord, UInteger> ID_PRODUCT = createField("id_product", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>ordernow.odn_order_product</code> table reference
     */
    public OdnOrderProduct() {
        this(DSL.name("odn_order_product"), null);
    }

    /**
     * Create an aliased <code>ordernow.odn_order_product</code> table reference
     */
    public OdnOrderProduct(String alias) {
        this(DSL.name(alias), ODN_ORDER_PRODUCT);
    }

    /**
     * Create an aliased <code>ordernow.odn_order_product</code> table reference
     */
    public OdnOrderProduct(Name alias) {
        this(alias, ODN_ORDER_PRODUCT);
    }

    private OdnOrderProduct(Name alias, Table<OdnOrderProductRecord> aliased) {
        this(alias, aliased, null);
    }

    private OdnOrderProduct(Name alias, Table<OdnOrderProductRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OdnOrderProduct(Table<O> child, ForeignKey<O, OdnOrderProductRecord> key) {
        super(child, key, ODN_ORDER_PRODUCT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ordernow.ORDERNOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ODN_ORDER_PRODUCT_ID_ORDER, Indexes.ODN_ORDER_PRODUCT_ID_PRODUCT, Indexes.ODN_ORDER_PRODUCT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OdnOrderProductRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_ODN_ORDER_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OdnOrderProductRecord> getPrimaryKey() {
        return Keys.KEY_ODN_ORDER_PRODUCT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OdnOrderProductRecord>> getKeys() {
        return Arrays.<UniqueKey<OdnOrderProductRecord>>asList(Keys.KEY_ODN_ORDER_PRODUCT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OdnOrderProductRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OdnOrderProductRecord, ?>>asList(Keys.ODN_ORDER_PRODUCT_IBFK_1, Keys.ODN_ORDER_PRODUCT_IBFK_2);
    }

    public OdnOrder odnOrder() {
        return new OdnOrder(this, Keys.ODN_ORDER_PRODUCT_IBFK_1);
    }

    public OdnProduct odnProduct() {
        return new OdnProduct(this, Keys.ODN_ORDER_PRODUCT_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderProduct as(String alias) {
        return new OdnOrderProduct(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnOrderProduct as(Name alias) {
        return new OdnOrderProduct(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OdnOrderProduct rename(String name) {
        return new OdnOrderProduct(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdnOrderProduct rename(Name name) {
        return new OdnOrderProduct(name, null);
    }
}
