/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables;


import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.Indexes;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.Keys;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.Ordernow;
import br.com.mathidios.springboot.jooq.docker.mysql.model.jooq.tables.records.OdnRestaurantRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdnRestaurant extends TableImpl<OdnRestaurantRecord> {

    private static final long serialVersionUID = -767669335;

    /**
     * The reference instance of <code>ordernow.odn_restaurant</code>
     */
    public static final OdnRestaurant ODN_RESTAURANT = new OdnRestaurant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OdnRestaurantRecord> getRecordType() {
        return OdnRestaurantRecord.class;
    }

    /**
     * The column <code>ordernow.odn_restaurant.id_restaurant</code>.
     */
    public final TableField<OdnRestaurantRecord, UInteger> ID_RESTAURANT = createField("id_restaurant", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>ordernow.odn_restaurant.nm_restaurant</code>.
     */
    public final TableField<OdnRestaurantRecord, String> NM_RESTAURANT = createField("nm_restaurant", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>ordernow.odn_restaurant.id_dishe</code>.
     */
    public final TableField<OdnRestaurantRecord, UInteger> ID_DISHE = createField("id_dishe", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>ordernow.odn_restaurant</code> table reference
     */
    public OdnRestaurant() {
        this(DSL.name("odn_restaurant"), null);
    }

    /**
     * Create an aliased <code>ordernow.odn_restaurant</code> table reference
     */
    public OdnRestaurant(String alias) {
        this(DSL.name(alias), ODN_RESTAURANT);
    }

    /**
     * Create an aliased <code>ordernow.odn_restaurant</code> table reference
     */
    public OdnRestaurant(Name alias) {
        this(alias, ODN_RESTAURANT);
    }

    private OdnRestaurant(Name alias, Table<OdnRestaurantRecord> aliased) {
        this(alias, aliased, null);
    }

    private OdnRestaurant(Name alias, Table<OdnRestaurantRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OdnRestaurant(Table<O> child, ForeignKey<O, OdnRestaurantRecord> key) {
        super(child, key, ODN_RESTAURANT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ordernow.ORDERNOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ODN_RESTAURANT_ID_DISHE, Indexes.ODN_RESTAURANT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OdnRestaurantRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_ODN_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OdnRestaurantRecord> getPrimaryKey() {
        return Keys.KEY_ODN_RESTAURANT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OdnRestaurantRecord>> getKeys() {
        return Arrays.<UniqueKey<OdnRestaurantRecord>>asList(Keys.KEY_ODN_RESTAURANT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OdnRestaurantRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OdnRestaurantRecord, ?>>asList(Keys.ODN_RESTAURANT_IBFK_1);
    }

    public OdnDishe odnDishe() {
        return new OdnDishe(this, Keys.ODN_RESTAURANT_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnRestaurant as(String alias) {
        return new OdnRestaurant(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdnRestaurant as(Name alias) {
        return new OdnRestaurant(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OdnRestaurant rename(String name) {
        return new OdnRestaurant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdnRestaurant rename(Name name) {
        return new OdnRestaurant(name, null);
    }
}
